Repository UnBArqDsw2020-2/2020.2_G2_Encare, pull requests merged in 2021-04, with the labels that each got.

#70 [#58] Gofs criacionais
  docs/Padroes_de_projeto/GOFs/gof_criacional.md
  docs/Padroes_de_projeto/GOFs/img/gof_criacional_v1.png
  docs/Padroes_de_projeto/GOFs/img/gof_criacional_v2.png
Labels: Arquitetura

#69 [#63] Aumento do escopo do projeto
  docs/Padroes_de_projeto/Escopo_aumentado.md
  docs/Padroes_de_projeto/img/Esboco_joao_pedro.png
  docs/Padroes_de_projeto/img/esboco_gustavo_nogueira.png
  docs/Padroes_de_projeto/img/esboco_joao_baraky.png
  docs/Padroes_de_projeto/img/esboco_renato_britto.png
  docs/Padroes_de_projeto/img/escopo_aumentado_v1.png
  docs/Padroes_de_projeto/img/escopo_aumentado_v2.png
  docs/Padroes_de_projeto/img/escopo_aumentado_v3.png
  docs/Padroes_de_projeto/img/escopo_up_use_cases.png
Labels: Arquitetura, Documentação, Produto

#73 [#55] Aplicar grasps
  docs/Padroes_de_projeto/GOFs/gof_criacional.md
  docs/Padroes_de_projeto/grasps/grasps.md
  docs/Padroes_de_projeto/grasps/images/Animal.png
  docs/Padroes_de_projeto/grasps/images/ContactData.png
  docs/Padroes_de_projeto/grasps/images/Openingv2.png
  docs/Padroes_de_projeto/grasps/images/Polimorfismo.png
  docs/Padroes_de_projeto/grasps/images/SequenceFeed.png
  docs/Padroes_de_projeto/grasps/images/SimpleClass.png
  docs/Padroes_de_projeto/grasps/images/SimpleClass01.png
  docs/Padroes_de_projeto/grasps/images/SimpleClass02.png
  docs/Padroes_de_projeto/grasps/images/SimpleClassE.png
  docs/Padroes_de_projeto/grasps/images/feedControllerConcept.png
  docs/Padroes_de_projeto/prototipos/imagens/Wireframe_home.jpg
  docs/Padroes_de_projeto/prototipos/imagens/Wireframe_perfil.jpg
  docs/Padroes_de_projeto/prototipos/imagens/prototipo-gustavo.png
  docs/Padroes_de_projeto/prototipos/imagens/prototipo-hugo-1.png
  docs/Padroes_de_projeto/prototipos/imagens/prototipo-hugo-2.png
  docs/Padroes_de_projeto/prototipos/imagens/prototipo-media-nicalo.jpg
  docs/Padroes_de_projeto/prototipos/prototipo_alta.md
  docs/assets/images/favicon-encare.svg
  docs/assets/images/logo-encare.png
  docs/assets/images/logo-encare.svg
  material/overrides/home.html
  mkdocs.yml
Labels: Arquitetura, Documentação

#74 [#64] Gofs comportamentais
  docs/Padroes_de_projeto/GOFs/gof_comportamental.md
  docs/Padroes_de_projeto/GOFs/images/Command.png
  docs/Padroes_de_projeto/GOFs/images/js-iterator.jpg
Labels: Arquitetura, Documentação

#71 [#65] Gofs estruturais
  docs/Padroes_de_projeto/GOFs/gof_criacional.md
  docs/Padroes_de_projeto/GOFs/gof_estrutural.md
  docs/Padroes_de_projeto/GOFs/img/gof_facade.png
  docs/Padroes_de_projeto/GOFs/img/gof_proxy.png
  mkdocs.yml
Labels: Arquitetura
